version: "3.8"
services:
  test-mysql:
    image: mysql:8.0
    container_name: test-mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
      MYSQL_ROOT_PASSWORD: rootpass
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10